dist: trusty
sudo: required
language: node_js
services:
  - mongodb
  - postgresql
sudo: required
node_js:
  - "0.11"
  - "0.10"
  - "4"
  - "5"
  - "6"
script: make test-once
addons:
  mongodb: "3.2"
  postgresql: "9.5"
before_script:
  - psql -U postgres -h localhost -p 5432 -c 'create database "agenda-test";'
  - sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - mongo --version
  - psql --version
after_script: make test-coveralls
before_install:
  # Travis uses an ancient GCC
  - export CC="gcc-4.9" CXX="g++-4.9"
  # node 0.8 comes with a non-functional version of npm
  - "if [[ $(node --version) == v0.8.* ]]; then npm install -g npm@2.1.18; fi"
